'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, RefreshCw, Building2, CircleCheck, Clock3, Circle, Plus, ChevronDown } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { jurisdictions, type PermitData, type Inspection, type Status } from '@/lib/inspections';
const examples=[{city:'Bellevue',number:'26 112569 BR'},{city:'Kirkland',number:'LSM25-02028'}];
const labels:Record<Status,string>={available:'Available',pending:'Pending',passed:'Passed'};
const icons={available:Circle,pending:Clock3,passed:CircleCheck};
function date(value:string){if(!value)return '—';const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function Badge({status}:{status:Status}){const Icon=icons[status];return <span className={`badge ${status}`}><Icon size={14}/>{labels[status]}</span>}
function RecordRow({row}:{row:Inspection}){return <TableRow><TableCell><details className="record"><summary><span className="inspection-name">{row.name}</span><ChevronDown size={16}/></summary><div className="record-detail"><p>{row.category}</p>{row.restriction&&<p>{row.restriction}</p>}{row.dates.length>0&&row.status==='available'&&<p>Available dates: {row.dates.map(date).join(' · ')}</p>}{row.history.length>0?<><h3>Inspection history</h3>{row.history.map((h,i)=><article key={i}><strong>{h.Status}</strong><span>{date(h.Date)}{h.Staff?` · ${h.Staff}`:''}</span>{h.Notes&&<p>{h.Notes}</p>}{h.DocumentUrl&&/^https:\/\/[^/]*mybuildingpermit\.com\//i.test(h.DocumentUrl)&&<a href={h.DocumentUrl} target="_blank" rel="noreferrer">View attachment ↗</a>}</article>)}</>:<p>No completed inspection records returned.</p>}</div></details></TableCell><TableCell><Badge status={row.status}/><span className="source-status">{row.sourceStatus}</span></TableCell><TableCell className="date-cell">{date(row.date|| (row.status==='available'?row.dates[0]:''))}<span className="source-status">{row.sourceStatus==='Scheduled'?'Scheduled':row.date?'Latest result':row.status==='available'&&row.dates.length?'Earliest available':''}</span></TableCell></TableRow>}
export default function Home(){
 const [permits,setPermits]=useState(examples),[selected,setSelected]=useState(0),[city,setCity]=useState('Bellevue'),[number,setNumber]=useState('');
 const [data,setData]=useState<PermitData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[filter,setFilter]=useState('all');
 const requestId=useRef(0); const active=permits[selected];
 const pull=useCallback(async(target:{city:string;number:string})=>{const id=++requestId.current;setLoading(true);setError('');setData(null);try{const response=await fetch(`/api/permits?${new URLSearchParams(target)}`);const result=await response.json() as PermitData & {error?:string};if(!response.ok)throw new Error(result.error||'Unable to load inspections.');if(id===requestId.current)setData(result);return result as PermitData;}catch(e){if(id===requestId.current)setError(e instanceof Error?e.message:'Unable to load inspections.');throw e;}finally{if(id===requestId.current)setLoading(false);}},[]);
 useEffect(()=>{setFilter('all');void pull(active).catch(()=>{});},[active,pull]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();const tool={name:'refresh_permit_inspections',description:'Refresh the selected permit from public MyBuildingPermit feeds and update the visible inspection list.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');const result=await pull(active);return {permit:result.number,city:result.city,fetchedAt:result.fetchedAt,counts:Object.fromEntries(Object.keys(labels).map(s=>[s,result.inspections.filter(r=>r.status===s).length]))};}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[active,pull]);
 const shown=data?.inspections.filter(r=>filter==='all'||r.status===filter)||[];
 const counts=Object.fromEntries(Object.keys(labels).map(s=>[s,data?.inspections.filter(r=>r.status===s).length||0]));
 function add(e:React.FormEvent){e.preventDefault();const value=number.trim().toUpperCase();if(!value)return;const existing=permits.findIndex(p=>p.city===city&&p.number===value);if(existing>=0){setSelected(existing);void pull(permits[existing]).catch(()=>{});}else{setPermits(p=>[...p,{city,number:value}]);setSelected(permits.length);}setNumber('');}
 return <main className="workspace"><header className="masthead"><div className="brand"><Building2 size={22}/> Permit desk</div><span>MYBUILDINGPERMIT · INSPECTIONS</span></header><section className="intro"><div><p className="eyebrow">PROJECT OVERVIEW</p><h1>Every inspection.<br/>One clear view.</h1></div><button className="refresh" disabled={loading} onClick={()=>void pull(active).catch(()=>{})}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Refreshing…':'Refresh inspections'}</button></section>
 <form className="permit-lookup" onSubmit={add}><div><label id="city-label">Jurisdiction</label><Select value={city} onValueChange={v=>v&&setCity(v)}><SelectTrigger aria-labelledby="city-label"><SelectValue/></SelectTrigger><SelectContent>{Object.keys(jurisdictions).map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select></div><div className="number-field"><label htmlFor="permit-number">Permit number</label><Input id="permit-number" placeholder="e.g. 26 112569 BR" value={number} onChange={e=>setNumber(e.target.value)} required maxLength={60} pattern="[A-Za-z0-9 -]+"/></div><button type="submit" className="lookup-button"><Plus size={17}/>Pull permit</button></form>
 <Tabs value={String(selected)} onValueChange={v=>setSelected(Number(v))}><TabsList className="project-tabs" aria-label="Tracked permits">{permits.map((p,i)=><TabsTrigger value={String(i)} key={`${p.city}:${p.number}`}>{p.city}<span>{p.number}</span></TabsTrigger>)}</TabsList></Tabs>
 <section className="project-heading"><div><p className="eyebrow">{active.city}</p><h2>{active.number}</h2>{data&&<p className="project-subtitle">{data.project}{data.address?` · ${data.address}`:''}</p>}</div><a href={data?.sourceUrl||`https://permitsearch.mybuildingpermit.com/PermitDetails/${encodeURIComponent(active.number)}/${encodeURIComponent(active.city)}`} target="_blank" rel="noreferrer">Open permit <ArrowUpRight size={16}/></a></section>
 <div className="summary">{(Object.keys(labels) as Status[]).map(status=>{const Icon=icons[status];return <div className={`metric ${status}`} key={status}><Icon size={20}/><span>{labels[status]}</span><strong>{data?counts[status]:'—'}</strong></div>})}</div>
 <section className="inspection-panel" aria-busy={loading}><div className="panel-heading"><h2>Inspections <span className="total-count">{data?.inspections.length??'—'}</span></h2><span aria-live="polite">{loading?'Pulling the latest records…':data?`Updated ${new Date(data.fetchedAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}`:'Not loaded'}</span></div><Tabs value={filter} onValueChange={v=>setFilter(String(v))}><TabsList variant="line" className="status-tabs" aria-label="Filter inspection status">{['all',...Object.keys(labels)].map(s=><TabsTrigger value={s} key={s}>{s==='all'?'All inspections':labels[s as Status]}</TabsTrigger>)}</TabsList></Tabs>
 {error?<div className="error-state" role="alert"><h3>Couldn’t load this permit</h3><p>{error}</p><button onClick={()=>void pull(active).catch(()=>{})}>Try again</button></div>:loading?<div className="loading-rows" aria-label="Loading inspections">{[1,2,3,4].map(i=><Skeleton className="h-12 w-full" key={i}/>)}</div>:<Table><TableHeader><TableRow><TableHead>INSPECTION / DETAILS</TableHead><TableHead>STATUS</TableHead><TableHead>DATE</TableHead></TableRow></TableHeader><TableBody>{shown.length?shown.map(row=><RecordRow key={row.id} row={row}/>):<TableRow><TableCell colSpan={3} className="empty-state">{data?'No inspections in this view.':'Choose a permit to view its inspections.'}</TableCell></TableRow>}</TableBody></Table>}
 </section><footer className="footnote"><p><strong>Available</strong> is offered for scheduling. <strong>Pending</strong> includes scheduled inspections, partial results, corrections, and restrictions. <strong>Passed</strong> includes approved and completed results.</p><p>Latest results take precedence over older attempts. Expand an inspection for the original status and notes. Available inspection types are not necessarily required for your project. MyBuildingPermit updates can be delayed.</p><a href="https://mybuildingpermit.com/" target="_blank" rel="noreferrer">Source: MyBuildingPermit ↗</a></footer></main>
}

