'use client';
import {useEffect,useRef,useState} from 'react';
import type {Inspection,PermitData} from '../lib/inspections';
import type {Live,Intent} from '../backend/mbp';
type View=Live & {inspections:Inspection[];fetchedAt:string;writesEnabled:boolean};
type Result={id:string;state:string;message:string;label:string;intent:Intent;expires:number};
const backend=process.env.NEXT_PUBLIC_ACTIONS_URL||'';
export function InspectionManagement({permit,onUpdate}:{permit:PermitData;onUpdate:(data:Pick<PermitData,'inspections'|'fetchedAt'>)=>void}){
 const [key,setKey]=useState(''),[live,setLive]=useState<View|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null),[intent,setIntent]=useState<Intent|null>(null),[ack,setAck]=useState(false);
 const actionRef=useRef<HTMLDivElement>(null),errorRef=useRef<HTMLParagraphElement>(null);
 const [openCount,setOpenCount]=useState(0);
 function openAction(next:Intent){setResult(null);setError('');setIntent(next);setAck(false);setOpenCount(n=>n+1);}
 useEffect(()=>{const panel=actionRef.current;if(panel&&(intent||result)){panel.focus({preventScroll:true});panel.scrollIntoView({block:'start'});}},[openCount,result?.id,result?.state]);
 useEffect(()=>{if(error){errorRef.current?.focus({preventScroll:true});errorRef.current?.scrollIntoView({block:'center'});}},[error]);
 const recoveryKey=`permit-action:${permit.city}:${permit.number}`;
 async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch(backend+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${key}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(110000)});const data=await response.json() as T & {error?:string};if(!response.ok)throw Error(data.error||'Backend request failed.');return data;}
 async function read(){const data:View=await api<View>('/live?'+new URLSearchParams({city:permit.city,number:permit.number}));setLive(data);onUpdate({inspections:data.inspections,fetchedAt:data.fetchedAt});}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}}
 async function unlock(){await read();const saved=localStorage.getItem(recoveryKey);if(saved){setResult(await api<Result>('/operations/'+saved));}}
 async function review(){if(!intent)return;const r:Result=await api<Result>('/review',{target:{city:permit.city,number:permit.number},intent});localStorage.setItem(recoveryKey,r.id);setResult(r);setAck(false);}
 async function confirm(){if(!result||!ack)return;const id=result.id;setResult({...result,state:'submitting',message:'Submitting once and checking MBP…'});try{const r:Result=await api<Result>('/confirm',{id,confirm:true});setResult(r);if(r.state==='succeeded')await read();}catch{setResult({...result,state:'unknown',message:'Connection lost. The request may have reached MBP. Check the result before doing anything else.'});}}
 async function check(){if(!result)return;const r:Result=await api('/operations/'+result.id);setResult(r);if(r.state==='succeeded')await read();}
 const unresolved=!!result&&['submitting','unknown'].includes(result.state);
 if(!backend)return <p className="request-notice">Scheduling and cancellation are awaiting secure backend setup. No requests can be submitted here yet.</p>;
 return <section className="inspection-management" aria-label="Manage inspections"><h2>Schedule or cancel on MyBuildingPermit</h2><p>Changes require a review and explicit confirmation. This panel reads current MBP availability.</p>
 {!live?<form onSubmit={e=>{e.preventDefault();void run(unlock);}}><label>Private management key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required/></label><button disabled={busy||!key}>Unlock management</button></form>:<>
 <button disabled={busy||unresolved} onClick={()=>void run(read)}>Refresh live availability</button><p>MBP checked {new Date(live.fetchedAt).toLocaleString()}</p>{!live.writesEnabled&&<p role="status">Backend is in read-only mode. Submissions are disabled.</p>}
 <h3>Scheduled inspections</h3>{!live.scheduled.length&&<p>No inspections currently scheduled in MBP.</p>}{live.scheduled.map(row=><div key={row.UniqueId} className="management-row"><span>{row.Description} · {row.InspectionDate.slice(0,10)}</span><button disabled={busy||unresolved||!live.writesEnabled||!row.InspectionCancellable} onClick={()=>{openAction({kind:'cancel',description:row.Description,date:row.InspectionDate.slice(0,10),bookingId:String(row.UniqueId)});}}>Review cancellation</button>{!row.InspectionCancellable&&<small>Contact {row.CancellationPhoneNumber||'the jurisdiction'} to cancel.</small>}</div>)}
 <h3>Request an inspection</h3>{live.inspections.map(row=>{const disabled=row.status==='passed'||row.restricted||!live.available.some(a=>a.Description===row.name)||live.scheduled.some(a=>a.Description===row.name);return <div key={row.id} className={`management-row ${disabled?'inspection-disabled':''}`}><span>{row.name} · {row.sourceStatus}</span><button disabled={disabled||busy||unresolved||!live.writesEnabled} onClick={()=>{openAction({kind:'schedule',description:row.name,date:'',name:'',phone:'',email:'',message:''});}}>Schedule</button>{row.restriction&&<small>{row.restriction}</small>}</div>;})}
 {(intent||result)&&<div className="action-focus" ref={actionRef} tabIndex={-1} aria-label="Inspection request details">
 {intent&&!result&&<form onSubmit={e=>{e.preventDefault();void run(review);}} className="action-review"><h3>{intent.kind==='cancel'?'Review cancellation':'Choose scheduling details'}</h3><p>{permit.city} · {permit.number} · {permit.address}</p><strong>{intent.description}</strong>{intent.kind==='schedule'?<><label>Date<select aria-label="Date" required value={intent.date} onChange={e=>setIntent({...intent,date:e.target.value})}><option value="">Choose a date</option>{live.available.find(r=>r.Description===intent.description)?.InspectionDates?.map(d=><option key={d} value={d.slice(0,10)}>{d.slice(0,10)}</option>)}</select></label><label>Site contact name<input required maxLength={100} value={intent.name} onChange={e=>setIntent({...intent,name:e.target.value})}/></label><label>Phone (10 digits)<input required inputMode="tel" pattern="[0-9]{10}" value={intent.phone} onChange={e=>setIntent({...intent,phone:e.target.value})}/></label><label>Email<input required type="email" value={intent.email} onChange={e=>setIntent({...intent,email:e.target.value})}/></label><label>Message to inspector<input maxLength={100} value={intent.message} onChange={e=>setIntent({...intent,message:e.target.value})}/></label></>:<p>{intent.date}</p>}<button disabled={busy}>Review request — does not submit</button><button type="button" disabled={busy} onClick={()=>setIntent(null)}>Back</button></form>}
 {result&&<div className="action-review" role="status"><h3>{result.label}</h3><p>{permit.city} · {permit.number} · {permit.address}</p><p>{result.message}</p>{result.state==='review'&&<><p>{result.intent.name} {result.intent.phone} {result.intent.email}</p><p>{result.intent.message}</p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I confirm this permit, inspection, and date.</label><button disabled={busy||!ack} onClick={()=>void run(confirm)}>{result.intent.kind==='cancel'?'Confirm cancellation':'Confirm scheduling'}</button><button disabled={busy} onClick={()=>{setResult(null);setAck(false);}}>Back to edit</button></>}{unresolved&&<button disabled={busy} onClick={()=>void run(check)}>Check result (does not resubmit)</button>}{['succeeded','failed'].includes(result.state)&&<button disabled={busy} onClick={()=>{localStorage.removeItem(recoveryKey);setResult(null);setIntent(null);}}>Done</button>}</div>}
 </div>}
 </>}{error&&<p ref={errorRef} tabIndex={-1} role="alert">{error}</p>}</section>;
}
